# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'shared', :path => ENV["LOCAL_KOTLIN_PATH"]

  # Pods for Ios
end
